language: node_js
node_js:
  - "stable"

notifications:
  email: false

dist: focal
sudo: false

services:
  - xvfb

addons:
  apt:
    packages:
     - fluxbox

before_script:
  - "export DISPLAY=:99.0"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  - stty cols 80
